/* ============================================================
   cards.js - the deck data (full 78-card deck)
   ------------------------------------------------------------
   The complete tarot deck: 22 Major Arcana + 56 Minor Arcana
   (Wands, Cups, Swords, Pentacles, Ace through King).

   This file is generated by gen_deck.py so the Minor Arcana
   stay perfectly consistent, but every meaning is hand-written
   in plain, friendly language. Edit gen_deck.py to change copy,
   then re-run it to regenerate this file.

   Each card object:
     - num     : numeral / rank shown on the card face
     - name    : the card's full name
     - emoji   : a simple glyph standing in for full artwork
     - suit    : "major" | "wands" | "cups" | "swords" | "pentacles"
     - keywords: 2–3 quick-glance themes (shown as little pills)
     - meaning : a friendly, plain-language reading (upright)

   The draw logic in main.js only reads these fields, so the
   deck can grow without touching any interaction code.
   ============================================================ */

const TAROT_DECK = [

  /* ---------- Major Arcana ---------- */
  {
    num: "0",
    name: "The Fool",
    emoji: "\u{1FAB6}",
    suit: "major",
    keywords: ["new beginnings", "trust", "leap"],
    meaning:
      "A fresh start is calling. The Fool says yes before knowing every step \u2014 take the leap with an open heart.",
  },
  {
    num: "I",
    name: "The Magician",
    emoji: "\u2728",
    suit: "major",
    keywords: ["power", "focus", "manifest"],
    meaning:
      "You already have the tools you need. Channel your focus and turn an idea into something real.",
  },
  {
    num: "II",
    name: "The High Priestess",
    emoji: "\u{1F319}",
    suit: "major",
    keywords: ["intuition", "mystery", "stillness"],
    meaning:
      "Get quiet and listen inward. Your intuition knows something your busy mind hasn't caught up to yet.",
  },
  {
    num: "III",
    name: "The Empress",
    emoji: "\u{1F338}",
    suit: "major",
    keywords: ["abundance", "nurture", "creativity"],
    meaning:
      "Something is blooming \u2014 a project, a bond, a softer season. Tend it gently and let it grow.",
  },
  {
    num: "IV",
    name: "The Emperor",
    emoji: "\u{1F3DB}\uFE0F",
    suit: "major",
    keywords: ["structure", "stability", "lead"],
    meaning:
      "Build the framework. A little structure right now turns scattered energy into steady progress.",
  },
  {
    num: "V",
    name: "The Hierophant",
    emoji: "\u{1F511}",
    suit: "major",
    keywords: ["tradition", "guidance", "learning"],
    meaning:
      "A mentor, teaching, or tried-and-true path has something to offer. There's wisdom in the well-worn road.",
  },
  {
    num: "VI",
    name: "The Lovers",
    emoji: "\u{1F495}",
    suit: "major",
    keywords: ["connection", "choice", "harmony"],
    meaning:
      "A meaningful choice about the heart \u2014 partnership, values, alignment. Choose what feels true to you.",
  },
  {
    num: "VII",
    name: "The Chariot",
    emoji: "\u{1F3C7}",
    suit: "major",
    keywords: ["drive", "willpower", "victory"],
    meaning:
      "Grab the reins. With determination and a clear direction, you can push through and win the day.",
  },
  {
    num: "VIII",
    name: "Strength",
    emoji: "\u{1F981}",
    suit: "major",
    keywords: ["courage", "patience", "soft power"],
    meaning:
      "True strength is gentle. Meet the hard thing with patience and compassion rather than force.",
  },
  {
    num: "IX",
    name: "The Hermit",
    emoji: "\u{1F56F}\uFE0F",
    suit: "major",
    keywords: ["reflection", "solitude", "inner light"],
    meaning:
      "Step back for a moment alone. The answer you're seeking comes from quiet reflection, not the crowd.",
  },
  {
    num: "X",
    name: "Wheel of Fortune",
    emoji: "\u{1F340}",
    suit: "major",
    keywords: ["change", "cycles", "luck"],
    meaning:
      "The wheel is turning in your favor. Stay open \u2014 a shift in luck or timing is on its way.",
  },
  {
    num: "XI",
    name: "Justice",
    emoji: "\u2696\uFE0F",
    suit: "major",
    keywords: ["fairness", "truth", "balance"],
    meaning:
      "Things are coming into balance. Act with honesty and the outcome will be fair to you.",
  },
  {
    num: "XII",
    name: "The Hanged Man",
    emoji: "\u{1FA9E}",
    suit: "major",
    keywords: ["pause", "new view", "surrender"],
    meaning:
      "A pause isn't a setback. Look at the situation from a new angle \u2014 the answer flips into view.",
  },
  {
    num: "XIII",
    name: "Death",
    emoji: "\u{1F98B}",
    suit: "major",
    keywords: ["endings", "rebirth", "release"],
    meaning:
      "Not literal \u2014 this is transformation. Let an old chapter close so a new one has room to begin.",
  },
  {
    num: "XIV",
    name: "Temperance",
    emoji: "\u{1F9EA}",
    suit: "major",
    keywords: ["balance", "patience", "blend"],
    meaning:
      "Find the middle path. Mixing patience with a little flexibility brings everything into harmony.",
  },
  {
    num: "XV",
    name: "The Devil",
    emoji: "\u{1F517}",
    suit: "major",
    keywords: ["habits", "honesty", "release"],
    meaning:
      "Notice what's holding you. A habit or fear feels binding only until you see you hold the key.",
  },
  {
    num: "XVI",
    name: "The Tower",
    emoji: "\u26A1",
    suit: "major",
    keywords: ["upheaval", "truth", "clearing"],
    meaning:
      "A sudden shake-up clears away what wasn't solid. It's startling, but it makes room for something truer.",
  },
  {
    num: "XVII",
    name: "The Star",
    emoji: "\u2B50",
    suit: "major",
    keywords: ["hope", "healing", "renewal"],
    meaning:
      "Breathe \u2014 the hard part is easing. The Star brings hope, healing, and a gentle return of faith.",
  },
  {
    num: "XVIII",
    name: "The Moon",
    emoji: "\u{1F311}",
    suit: "major",
    keywords: ["dreams", "intuition", "mystery"],
    meaning:
      "Things aren't fully clear yet, and that's okay. Trust your dreams and instincts to light the path.",
  },
  {
    num: "XIX",
    name: "The Sun",
    emoji: "\u2600\uFE0F",
    suit: "major",
    keywords: ["joy", "success", "warmth"],
    meaning:
      "Pure sunshine. Joy, clarity, and success are shining on you \u2014 enjoy this bright, open moment.",
  },
  {
    num: "XX",
    name: "Judgement",
    emoji: "\u{1F4EF}",
    suit: "major",
    keywords: ["awakening", "calling", "renewal"],
    meaning:
      "A wake-up call invites you to rise. Reflect on how far you've come and answer what's calling you forward.",
  },
  {
    num: "XXI",
    name: "The World",
    emoji: "\u{1F30D}",
    suit: "major",
    keywords: ["completion", "wholeness", "celebrate"],
    meaning:
      "A cycle completes. Take a bow \u2014 you've come full circle, and the whole world feels open again.",
  },

  /* ---------- Minor Arcana: Wands 🔥 ---------- */
  {
    num: "Ace",
    name: "Ace of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["spark", "new idea", "energy"],
    meaning:
      "A bright new spark of energy or inspiration arrives. Say yes to the idea that's making your hands itch to start.",
  },
  {
    num: "Two",
    name: "Two of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["planning", "choice", "horizon"],
    meaning:
      "You're standing at the edge of something, map in hand. Pick a direction and let yourself imagine the bigger picture.",
  },
  {
    num: "Three",
    name: "Three of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["progress", "expansion", "wait"],
    meaning:
      "The first efforts are paying off. Ships are on their way back \u2014 keep looking outward and trust your momentum.",
  },
  {
    num: "Four",
    name: "Four of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["celebration", "home", "milestone"],
    meaning:
      "A happy little milestone to celebrate. Pause and enjoy the warmth of people and place before the next push.",
  },
  {
    num: "Five",
    name: "Five of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["friction", "competition", "scrappy"],
    meaning:
      "A bit of friction or rivalry stirs things up. It's noisy, not dangerous \u2014 find a way to play that's still fair.",
  },
  {
    num: "Six",
    name: "Six of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["recognition", "success", "pride"],
    meaning:
      "A well-earned win, and others notice. Let yourself be seen and enjoy the moment of recognition.",
  },
  {
    num: "Seven",
    name: "Seven of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["standing firm", "defense", "conviction"],
    meaning:
      "You've got the higher ground \u2014 hold it. It's worth defending what you've built when you believe in it.",
  },
  {
    num: "Eight",
    name: "Eight of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["momentum", "speed", "news"],
    meaning:
      "Things move fast now. Messages, travel, or quick progress \u2014 ride the momentum while it's flowing.",
  },
  {
    num: "Nine",
    name: "Nine of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["resilience", "one more push", "guard"],
    meaning:
      "You're tired but close. One more round of effort, and a little self-protection, will carry you through.",
  },
  {
    num: "Ten",
    name: "Ten of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["burden", "almost there", "delegate"],
    meaning:
      "You're carrying a lot. The finish line is near \u2014 set down what isn't yours to hold and ask for a hand.",
  },
  {
    num: "Page",
    name: "Page of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["curiosity", "exploration", "spark"],
    meaning:
      "A curious, playful messenger. Follow the thing that excites you, even before you know where it leads.",
  },
  {
    num: "Knight",
    name: "Knight of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["adventure", "passion", "bold"],
    meaning:
      "Bold, restless energy ready to charge ahead. Channel the fire so your enthusiasm doesn't outrun your plan.",
  },
  {
    num: "Queen",
    name: "Queen of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["confidence", "warmth", "magnetism"],
    meaning:
      "Warm, self-assured, and magnetic. Lead with your natural glow and people will gather around it.",
  },
  {
    num: "King",
    name: "King of Wands",
    emoji: "\u{1F525}",
    suit: "wands",
    keywords: ["vision", "leadership", "drive"],
    meaning:
      "A visionary who turns passion into direction. Take charge of your own big idea with steady confidence.",
  },

  /* ---------- Minor Arcana: Cups 💧 ---------- */
  {
    num: "Ace",
    name: "Ace of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["new love", "openness", "feeling"],
    meaning:
      "A cup overflowing with new feeling \u2014 love, compassion, or creative joy. Let your heart open to it.",
  },
  {
    num: "Two",
    name: "Two of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["partnership", "mutual", "bond"],
    meaning:
      "A genuine meeting of hearts. Mutual respect and care flow both ways \u2014 cherish this connection.",
  },
  {
    num: "Three",
    name: "Three of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["friendship", "joy", "community"],
    meaning:
      "Good friends, good company, something to toast. Lean into the people who celebrate you.",
  },
  {
    num: "Four",
    name: "Four of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["apathy", "reflection", "reset"],
    meaning:
      "Feeling a little checked-out or restless. Sit with it \u2014 and notice the offer you might be overlooking.",
  },
  {
    num: "Five",
    name: "Five of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["disappointment", "grief", "perspective"],
    meaning:
      "Something didn't go as hoped, and that's worth grieving. Two cups still stand \u2014 turn and see what remains.",
  },
  {
    num: "Six",
    name: "Six of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["nostalgia", "comfort", "kindness"],
    meaning:
      "A warm wave of nostalgia or a kind gesture from the past. Let sweetness and simple comfort find you.",
  },
  {
    num: "Seven",
    name: "Seven of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["options", "daydreams", "clarity"],
    meaning:
      "So many tempting choices, some real and some just shiny. Get clear on what you actually want before you reach.",
  },
  {
    num: "Eight",
    name: "Eight of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["walking away", "seeking more", "growth"],
    meaning:
      "You're ready to leave behind what no longer fills you. Walking toward something deeper takes quiet courage.",
  },
  {
    num: "Nine",
    name: "Nine of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["contentment", "wish", "satisfaction"],
    meaning:
      "The 'wish card' \u2014 a deep, satisfied contentment. Savor having what you hoped for.",
  },
  {
    num: "Ten",
    name: "Ten of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["harmony", "belonging", "joy"],
    meaning:
      "Emotional fullness and belonging \u2014 the happy-home feeling. Soak in the warmth of your people.",
  },
  {
    num: "Page",
    name: "Page of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["wonder", "tenderness", "message"],
    meaning:
      "A tender, dreamy messenger. A sweet idea or gentle invitation may arrive \u2014 stay open to it.",
  },
  {
    num: "Knight",
    name: "Knight of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["romance", "following heart", "grace"],
    meaning:
      "A romantic, idealistic mover who leads with the heart. Follow what you love, gracefully.",
  },
  {
    num: "Queen",
    name: "Queen of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["compassion", "intuition", "care"],
    meaning:
      "Deeply caring and intuitive. Trust your feelings and offer yourself the same tenderness you give others.",
  },
  {
    num: "King",
    name: "King of Cups",
    emoji: "\u{1F4A7}",
    suit: "cups",
    keywords: ["calm", "balance", "emotional mastery"],
    meaning:
      "Steady at the emotional helm. Stay calm and kind under pressure and others will feel safe with you.",
  },

  /* ---------- Minor Arcana: Swords 🗡️ ---------- */
  {
    num: "Ace",
    name: "Ace of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["clarity", "truth", "breakthrough"],
    meaning:
      "A sudden clear thought cuts through the fog. A breakthrough or honest truth gives you fresh direction.",
  },
  {
    num: "Two",
    name: "Two of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["stalemate", "decision", "weigh"],
    meaning:
      "Stuck between two options with a blindfold on. Take the blindfold off \u2014 you have more information than you think.",
  },
  {
    num: "Three",
    name: "Three of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["heartache", "release", "healing"],
    meaning:
      "A painful truth or heartache. Let yourself feel it; naming the hurt is the first step to it easing.",
  },
  {
    num: "Four",
    name: "Four of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["rest", "recovery", "pause"],
    meaning:
      "Time to genuinely rest. Step back and let your mind recover \u2014 you'll think clearer for it.",
  },
  {
    num: "Five",
    name: "Five of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["conflict", "ego", "let go"],
    meaning:
      "A win that doesn't feel like one, or a fight not worth it. Ask whether being right is worth the cost.",
  },
  {
    num: "Six",
    name: "Six of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["transition", "moving on", "calmer waters"],
    meaning:
      "Moving away from rougher waters toward calm. The journey forward is gentle, even if leaving was hard.",
  },
  {
    num: "Seven",
    name: "Seven of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["strategy", "caution", "honesty"],
    meaning:
      "A nudge toward cleverness \u2014 or a warning to watch for it. Choose the honest path; shortcuts have a way of unraveling.",
  },
  {
    num: "Eight",
    name: "Eight of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["feeling stuck", "self-doubt", "freedom"],
    meaning:
      "The trap feels tighter than it is. Look closely \u2014 the way out has been within reach all along.",
  },
  {
    num: "Nine",
    name: "Nine of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["worry", "anxiety", "dawn"],
    meaning:
      "Late-night worries can loom large. Most of these fears feel smaller in daylight \u2014 be gentle with your mind.",
  },
  {
    num: "Ten",
    name: "Ten of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["rock bottom", "ending", "sunrise"],
    meaning:
      "A hard ending, fully felt. The good news hidden here: it can't get worse, and a new dawn is already coming.",
  },
  {
    num: "Page",
    name: "Page of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["curiosity", "truth-seeking", "alert"],
    meaning:
      "A sharp, curious mind hungry for the truth. Ask the questions \u2014 just keep your words kind.",
  },
  {
    num: "Knight",
    name: "Knight of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["focus", "ambition", "slow down"],
    meaning:
      "Fast, focused, and direct \u2014 charging toward a goal. Make sure you're aimed well before you race off.",
  },
  {
    num: "Queen",
    name: "Queen of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["clear-eyed", "honest", "independent"],
    meaning:
      "Clear-eyed and fair, with healthy boundaries. Speak your truth directly and lead with level-headed kindness.",
  },
  {
    num: "King",
    name: "King of Swords",
    emoji: "\u{1F5E1}\uFE0F",
    suit: "swords",
    keywords: ["logic", "fairness", "authority"],
    meaning:
      "Wise, fair, and grounded in clear thinking. Make the call with both your head and your principles.",
  },

  /* ---------- Minor Arcana: Pentacles 🪙 ---------- */
  {
    num: "Ace",
    name: "Ace of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["opportunity", "new venture", "seed"],
    meaning:
      "A solid new opportunity \u2014 a job, a plan, a tangible seed. Plant it; this one has real roots.",
  },
  {
    num: "Two",
    name: "Two of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["juggling", "balance", "flexibility"],
    meaning:
      "Juggling a couple of things at once. Stay light on your feet and the balance holds just fine.",
  },
  {
    num: "Three",
    name: "Three of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["teamwork", "skill", "building"],
    meaning:
      "Good work taking shape through collaboration. Your skill is valued \u2014 keep building together.",
  },
  {
    num: "Four",
    name: "Four of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["security", "holding on", "loosen"],
    meaning:
      "Holding tight to what feels safe. A little security is wise; just don't grip so hard nothing new can come in.",
  },
  {
    num: "Five",
    name: "Five of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["hardship", "support", "reach out"],
    meaning:
      "A lean or lonely stretch. Help is closer than it looks \u2014 the lit window is right there; reach out.",
  },
  {
    num: "Six",
    name: "Six of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["generosity", "fairness", "flow"],
    meaning:
      "Giving and receiving find their balance. Whether you're sharing or being supported, let it flow kindly.",
  },
  {
    num: "Seven",
    name: "Seven of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["patience", "assessment", "long game"],
    meaning:
      "You've planted; now you wait and tend. Step back, assess honestly, and trust the slow growth.",
  },
  {
    num: "Eight",
    name: "Eight of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["craft", "diligence", "mastery"],
    meaning:
      "Heads-down, steady practice. Care about the details \u2014 you're quietly getting very good at this.",
  },
  {
    num: "Nine",
    name: "Nine of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["self-reliance", "comfort", "enjoy"],
    meaning:
      "Earned comfort and independence. Enjoy the fruits of your own effort \u2014 you built this garden.",
  },
  {
    num: "Ten",
    name: "Ten of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["stability", "legacy", "abundance"],
    meaning:
      "Lasting security and the warmth of roots. Wealth here is also family, home, and things that endure.",
  },
  {
    num: "Page",
    name: "Page of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["study", "ambition", "new skill"],
    meaning:
      "A studious, ambitious messenger. A chance to learn something practical \u2014 start, and stay curious.",
  },
  {
    num: "Knight",
    name: "Knight of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["reliability", "routine", "patience"],
    meaning:
      "Dependable and methodical, in for the long haul. Slow and steady really does win this one.",
  },
  {
    num: "Queen",
    name: "Queen of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["nurturing", "practical", "grounded"],
    meaning:
      "Warm, capable, and down-to-earth. Tend to both your work and your wellbeing \u2014 you're good at both.",
  },
  {
    num: "King",
    name: "King of Pentacles",
    emoji: "\u{1FA99}",
    suit: "pentacles",
    keywords: ["abundance", "security", "provider"],
    meaning:
      "Grounded success and steady provision. You've built something solid; lead it generously.",
  },
];